AEwebshop/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('ar/', views.ArHomeView.as_view(), name='ar-home'),
    path('en/', views.EnHomeView.as_view(), name='en-home'),
    path('ar/products/<slug>/', views.ArItemDetailView.as_view(), name='ar-products'),
    path('en/products/<slug>/', views.EnItemDetailView.as_view(), name='en-products'),
    path('ar/checkout/', views.ArCheckoutView.as_view(), name='ar-checkout'),
    path('en/checkout/', views.EnCheckoutView.as_view(), name='en-checkout'),
    path('ar/order-summary/', views.ArOrderSummaryView.as_view(), name='ar-order-summary'),
    path('en/order-summary/', views.EnOrderSummaryView.as_view(), name='en-order-summary'),
    path('ar/add-to-cart/<slug>/', views.ar_add_to_cart, name='ar-add-to-cart'),
    path('en/add-to-cart/<slug>/', views.en_add_to_cart, name='en-add-to-cart'),
    path('en/add-coupon/', views.AddCouponView.as_view(), name='add-en-coupon'),
    path('ar/add-coupon/', views.ArAddCouponView.as_view(), name='add-ar-coupon'),
    path('ar/remove-from-cart/<slug>/', views.ar_remove_from_cart, name='ar-remove-from-cart'),
    path('en/remove-from-cart/<slug>/', views.en_remove_from_cart, name='en-remove-from-cart'),
    path('ar/add-item-to-cart/<slug>/', views.ar_add_item_to_cart, name='ar-add-item-to-cart'),
    path('en/add-item-to-cart/<slug>/', views.en_add_item_to_cart, name='en-add-item-to-cart'),
    path('ar/remove-item-from-cart/<slug>/', views.ar_remove_item_from_cart, name='ar-remove-item-from-cart'),
    path('en/remove-item-from-cart/<slug>/', views.en_remove_item_from_cart, name='en-remove-item-from-cart'),
    path('ar/remove-all-from-cart/<slug>/', views.ar_remove_all_from_cart, name='ar-remove-all-from-cart'),
    path('en/remove-all-from-cart/<slug>/', views.en_remove_all_from_cart, name='en-remove-all-from-cart'),
    path('ar/payment/<ar_payment_option>/', views.ArPaymentView.as_view(), name='ar-payment'),
    path('payment/<en_payment_option>/', views.PaymentView.as_view(), name='en-payment'),
    path('request-refund/', views.RequestRefundView.as_view(), name='request-refund'),
    path('ar/delivery/<ar_payment_option>', views.ArDeliveryView.as_view(), name='ar-delivery'),
    path('en/delivery/<en_payment_option>', views.EnDeliveryView.as_view(), name='en-delivery'),
    path('en/deliver-from-cart/<slug>/', views.en_deliver_from_cart, name='en-deliver-from-cart'),
    path('ar/deliver-from-cart/<slug>/', views.ar_deliver_from_cart, name='ar-deliver-from-cart')
]

AEwebshop/eshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core'))
]

urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

AEwebshop/core/models.py
from django.db.models.signals import post_save
from django.conf import settings
from django.db import models
from django.db.models import Sum
from django.shortcuts import reverse
from django_countries.fields import CountryField
from django.forms import ModelForm

CATEGORY_CHOICES = (
    ('S', 'Shirt'),
    ('SW', 'Sport wear'),
    ('OW', 'Outwear'),
    ('NU', 'Numbers')
)
AR_CATEGORY_CHOICES = (
    ('S', 'ملابس شبابيه'),
    ('SW', 'ملابس رياضية'),
    ('OW', 'ملابس للخروج'),
    ('NU', "ارقام")
)
LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger')
)
AR_LABEL_CHOICES = (
    ('P', 'اولى'),
    ('S', 'ثانوى'),
    ('D', 'خطر')
)

ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shipping')
)


class UserProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    stripe_customer_id = models.CharField(max_length=50, blank=True, null=True)
    one_click_purchasing = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username


class Item(models.Model):
    title = models.CharField(max_length=100)
    ar_title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=4)
    ar_category = models.CharField(choices=AR_CATEGORY_CHOICES, max_length=4)
    label = models.CharField(choices=LABEL_CHOICES, max_length=4)
    ar_label = models.CharField(choices=AR_LABEL_CHOICES, max_length=4)
    description = models.TextField()
    ar_description = models.TextField()
    slug = models.SlugField()
    image = models.ImageField()

    def __str__(self):
        return self.title

    def get_ar_absolute_url(self):
        return reverse('core:ar-products', kwargs={
            'slug': self.slug
        })

    def get_en_absolute_url(self):
        return reverse('core:en-products', kwargs={
            'slug': self.slug
        })

    def get_ar_add_to_cart_url(self):
        return reverse('core:ar-add-to-cart', kwargs={
            'slug': self.slug
        })

    def get_en_add_to_cart_url(self):
        return reverse('core:en-add-to-cart', kwargs={
            'slug': self.slug
        })

    def get_ar_remove_from_cart_url(self):
        return reverse('core:ar-remove-from-cart', kwargs={
            'slug': self.slug
        })

    def get_en_remove_from_cart_url(self):
        return reverse('core:en-remove-from-cart', kwargs={
            'slug': self.slug
        })


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    ordered = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    ref_code = models.CharField(max_length=20)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    billing_address = models.ForeignKey('Address', related_name='billing_address', on_delete=models.SET_NULL,
                                        blank=True, null=True)
    shipping_address = models.ForeignKey('Address', related_name='shipping_address', on_delete=models.SET_NULL,
                                         blank=True, null=True)
    payment = models.ForeignKey('Payment', on_delete=models.SET_NULL, blank=True, null=True)
    coupon = models.ForeignKey('Coupon', on_delete=models.SET_NULL, blank=True, null=True)
    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    def get_total_price(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        if self.coupon:
            total -= self.coupon.amount
        return total


class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    customer_name = models.CharField(max_length=100, null=True)
    phone = models.IntegerField(null=True)
    email = models.EmailField(null=True, blank=True)
    street_address = models.CharField(max_length=250, null=True)
    apartment_address = models.CharField(max_length=250, null=True, blank=True)
    country = CountryField(multiple=False, null=True, blank=True)
    zip = models.CharField(max_length=100, null=True, blank=True)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = 'Addresses'


class CheckoutForm(ModelForm):
    class Meta:
        model = Address
        fields = ['customer_name', 'phone', 'street_address', 'country']


class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=150)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username


class Coupon(models.Model):
    code = models.CharField(max_length=30)
    amount = models.FloatField()

    def __str__(self):
        return self.code


class Refund(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    reason = models.TextField()
    accepted = models.BooleanField(default=False)
    customer_name = models.CharField(max_length=100, null=True)
    phone = models.IntegerField(null=True)
    email = models.EmailField()

    def __str__(self):
        return f"{self.pk}"


def userprofile_receiver(sender, instance, created, *args, **kwargs):
    if created:
        userprofile = UserProfile.objects.create(user=instance)


post_save.connect(userprofile_receiver, sender=settings.AUTH_USER_MODEL)

AEwebshop/templates/ar-delivery.html
{% extends 'ar-base.html' %}
{% load static %}
{% block content %}
<label class="btn btn-primary"> تأكد من معلومات الشحن كما يمكنك الرجوع للخلف للتصحيح:</label>


                        {% for order_item in object.items.all %}
                       <li>User name: {{ order_item.user }}.</li>
                       <li>Item names: {{ order_item.item.title }}.</li>
                     <li>Item image: <img src="{{ order_item.item.image.url }}"</li>
                       <li>Item quantity: {{ order_item.quantity }}.</li>
                           {% if order_item.item.discount_price %}

                               <li>Total item price: {{ order_item.get_total_discount_item_price }}EGP</li>
                                        <span class="badge badge-primary">saving {{ order_item.get_amount_saved }}EGP</span>
                                      {% else %}

                               <li>Total item price: {{ order_item.get_total_item_price }}EGP</li>

                              {% endif %}
                            <li>Deliver to the indicated shipping address:<a href="{% url 'core:ar-deliver-from-cart' slug=order_item.item.slug %}"><i class="fas fa-truck ml-2"></i></a></li>

                        {% endfor %}
                       <li>Total price: {{ object.get_total_price }}EGP</li>

               <button class="" type="submit" Place an order ></button>
          </form>
      {% endblock %}

AEwebshop/templates/ar-product-page.html
{% extends 'ar-base.html' %}
{% load static %}
{% block content %}


  <!--Main layout-->
  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/14.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="p-4">

            <div class="mb-3">
              <a href="">
                <span class="badge purple mr-1">{{ object.get_ar_category_display }}</span>
              </a>

            </div>

            <p class="lead">
              <span class="mr-1">

              </span>

                {% if object.discount_price %}
                  <span>${{ object.discount_price }}</span>
                  <del>${{ object.price}}</del>
                {%else%}
                   <span>${{ object.price }}</span>
               {% endif %}

            </p>

            <p class="lead font-weight-bold">عن المنتج</p>

            <p>{{ object.ar_description }}</p>


          </div>
          <a href="{{ object.get_ar_add_to_cart_url }}" class="btn btn-primary btn-md my-0 p" >
            اضف الى العربه
                <i class="fas fa-shopping-cart ml-1"></i>
              </a>

          <a href="{{ object.get_ar_remove_from_cart_url }}" class="btn btn-danger btn-md my-0 p" >
            احذف من العربه

              </a>

          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <hr>

    </div>
  </main>

{% endblock content %}

AEwebshop/templates/en-base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
   <title>{% block head_title %}{% endblock %}</title>
    {% block extra_head %}
    {% endblock %}      <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
  <!-- Bootstrap core CSS -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <!-- Your custom styles (optional) -->
  <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

  </style>
</head>

{% include "en-navbar.html" %}
<body>


<div class="mt-5 pt-4">
    {% if messages %}

    {% for message in messages %}
      <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    {% endfor %}

{% endif %}
</div>
{% block content %}
{% endblock content %}
    {% block extra_body %}
    {% endblock %}


{% include "footer.html" %}
{% include "scripts.html" %}
{% block extra_scripts %}
{% endblock extra_scripts %}
</body>
</html>

AEwebshop/templates/en-navbar.html
{% load cart_template_tags %}
{% load static %}
{% load socialaccount %}
{% providers_media_js %}


  <!-- Navbar -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">

      <!-- Brand -->
      <a class="navbar-brand waves-effect" href="/" target="_blank">
        <strong class="blue-text">E-shop</strong>
      </a>

      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Left -->
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link waves-effect" href="/en/">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="/en/checkout/" target="_blank">Checkout</a>
          </li>

        </ul>

        <!-- Right -->
        <ul class="navbar-nav nav-flex-icons">
            {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a href="{% url 'core:en-order-summary' %}" class="nav-link waves-effect">
              <span class="badge red z-depth-1 mr-1"> {{ request.user|cart_item_count }} </span>
              <i class="fas fa-shopping-cart"></i>
              <span class="clearfix d-none d-sm-inline-block"> Cart </span>
            </a>
          </li>
            <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_logout' %}">
               <span class="clearfix d-none d-sm-inline-block"> Logout </span>
            </a>
          </li>
            {% else %}
            <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_login' %}">
               <span class="clearfix d-none d-sm-inline-block"> Login </span>
            </a>
          </li>
            <li class="nav-item">
          <a class="nav-link waves-effect" href="{% provider_login_url "facebook" method="js_sdk" %}">
           <span class="clearfix d-none d-sm-inline-block"> Facebook login </span>
            </a>
        </li>
            <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_signup' %}">
               <span class="clearfix d-none d-sm-inline-block"> Signup </span>
            </a>
          </li>
          {% endif %}
         </ul>

      </div>

    </div>
  </nav>
  <!-- Navbar -->

AEwebshop/templates/en-order-summary.html
{% extends 'en-base.html' %}
{% load static %}
{% block content %}


  <!--Main layout-->
  <main>
    <div class="container">

        <div class="table-responsive text-nowrap">
  <h1>Order summary<span class="badge badge-primary"></span></h1>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Item title</th>
        <th scope="col">Item price</th>
        <th scope="col">Quantity</th>
        <th scope="col">Total item price</th>
      </tr>
    </thead>
    <tbody>

        {% for order_item in object.items.all %}
        <tr>
          <th scope="row">{{ forloop.counter }}</th>
        <td><span class="badge badge-success">{{ order_item.item.title }}</span></td>
            <td><span class="badge badge-light">{{ order_item.item.price }}EGP</span></td>
        <td>
            <a href="{% url 'core:en-add-item-to-cart' slug=order_item.item.slug %}"><i class="fas fa-plus ml-2"></i></a>
            {{ order_item.quantity }}
            <a href="{% url 'core:en-remove-item-from-cart' slug=order_item.item.slug %}"><i class="fas fa-minus mr-2"></i></a>
        </td>
        <td>
          {% if order_item.item.discount_price %}

          {{ order_item.get_total_discount_item_price }}EGP
            <span class="badge badge-dark">saving {{ order_item.get_amount_saved }}EGP</span>
          {% else %}

          {{ order_item.get_total_item_price }}EGP

          {% endif %}
        </td>
            <td>
                <a style="color: red;"  href="{% url 'core:en-remove-all-from-cart' order_item.item.slug %}"><i class="fas fa-trash float-right"></i></sa>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="4"> <span class="badge badge-danger">Your cart is empty </span></td>
        </tr>
        <tr>
            <td colspan="4">
                <a class="btn btn-primary float-right" href="/en/"><b>Continue shopping</b></a>
            </td>
        </tr>
        {% endfor %}
        <tr>{% if object.coupon %}

        <td colspan="4"><b>coupon</b></td>
        <td><b>{{ object.coupon.amount }}EGP</b></td>

        {% endif %}</tr>
    <tr>
        {% if object.get_total_price %}
        <td colspan="4"><b>Total price</b></td>
        <td><span class="badge badge-primary">{{ object.get_total_price }}EGP</span></td>
    </tr>
    <td colspan="5">
        <a class="btn btn-warning float-right ml-2"href="/en/checkout/"><b>Proceed to checkout</b></a>
        <a class="btn btn-primary float-right" href="/en/"><b>Continue shopping</b></a>
    </td>
    {% endif %}
    </tbody>
  </table>

</div>

    </div>
  </main>
  <!--Main layout-->

{% endblock content %}

AEwebshop/templates/en-product-page.html
{% extends 'en-base.html' %}
{% load static %}
{% block content %}


  <!--Main layout-->
  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/14.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="p-4">

            <div class="mb-3">
              <a href="">
                <span class="badge purple mr-1">{{ object.get_category_display }}</span>
              </a>

            </div>

            <p class="lead">
              <span class="mr-1">

              </span>

                {% if object.discount_price %}
                  <span>${{ object.discount_price }}</span>
                  <del>${{ object.price}}</del>
                {%else%}
                   <span>${{ object.price }}</span>
               {% endif %}

            </p>

            <p class="lead font-weight-bold">Description</p>

            <p>{{ object.description }}</p>


          </div>
          <a href="{{ object.get_en_add_to_cart_url }}" class="btn btn-primary btn-md my-0 p" >
            Add to cart
                <i class="fas fa-shopping-cart ml-1"></i>
              </a>

          <a href="{{ object.get_en_remove_from_cart_url }}" class="btn btn-danger btn-md my-0 p" >
            Remove from cart

              </a>

          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <hr>


    </div>
  </main>
  <!--Main layout-->

{% endblock content %}

AEwebshop/templates/footer.html
{% load static %}


  <!--Footer-->
  <footer class="page-footer text-center font-small mt-4 wow fadeIn">


    <hr class="my-4">

    <!-- Social icons -->
    <div class="pb-4">
      <a href="https://www.facebook.com/mdbootstrap" target="_blank">
        <i class="fab fa-facebook-f mr-3"></i>
      </a>

      <a href="https://twitter.com/MDBootstrap" target="_blank">
        <i class="fab fa-twitter mr-3"></i>
      </a>

      <a href="https://www.youtube.com/watch?v=7MUISDJ5ZZ4" target="_blank">
        <i class="fab fa-youtube mr-3"></i>
      </a>

      <a href="https://plus.google.com/u/0/b/107863090883699620484" target="_blank">
        <i class="fab fa-google-plus-g mr-3"></i>
      </a>

      <a href="https://dribbble.com/mdbootstrap" target="_blank">
        <i class="fab fa-dribbble mr-3"></i>
      </a>

      <a href="https://pinterest.com/mdbootstrap" target="_blank">
        <i class="fab fa-pinterest mr-3"></i>
      </a>

      <a href="https://github.com/mdbootstrap/bootstrap-material-design" target="_blank">
        <i class="fab fa-github mr-3"></i>
      </a>

      <a href="http://codepen.io/mdbootstrap/" target="_blank">
        <i class="fab fa-codepen mr-3"></i>
      </a>
    </div>
    <!-- Social icons -->

    <!--Copyright-->
    <div class="footer-copyright py-3">
      © 2019 Copyright:
      <a href="https://mdbootstrap.com/education/bootstrap/" target="_blank"> MDBootstrap.com </a>
    </div>
    <!--/.Copyright-->

  </footer>
  <!--/.Footer-->

AEwebshop/templates/home-multilingual.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <!-- Your custom styles (optional) -->
  <link href="{% static 'css/style.min.css' %}" rel="stylesheet">

<div class="mt-5 pt-4">


    <title>
     Electronic web-shop!
    </title>
</head>

    <div class="col-md-16 mb-4">
<div class="card" style="width: 18rem;">
  <img src="/media/english.jpg" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">Welcome</h5>
    <p class="card-text">The electronic shop.</p>
    <a href="{% url 'core:en-home' %}" class="btn btn-primary stretched-link">For english click here</a>
  </div>
</div>
</div>
    <div class="col-md-16 mb-4">
<div class="card" style="width: 18rem;">
  <img src="/media/arabic.png" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">مرحبا</h5>
    <p class="card-text">المتجر الالكترونى</p>
    <a href="{% url 'core:ar-home' %}" class="btn btn-primary stretched-link">للغة العربية اضغط هنــا</a>
  </div>
</div>
    </div>

AEwebshop/templates/item_list.html
{% extends 'base.html' %}

{% block content %}

<h1>Here is the list of items</h1>

{% for item in items_list %}
{{ item }}
{% endfor %}
{% endblock content %}

AEwebshop/templates/order_snippet.html
       <!--Grid column-->
        <div class="col-md-12 mb-4">

          <!-- Heading -->
          <h4 class="d-flex justify-content-between align-items-center mb-3">
            <button type="button" class="btn btn-primary">Your cart</button>
            <span class="badge badge-primary badge-pill">{{ order.items.count }}</span>

          </h4>

          <!-- Cart -->
          <ul class="list-group mb-3 z-depth-1">
            {% for order_item in order.items.all %}
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                  <span class="btn btn-light">{{ order_item.quantity }} x {{ order_item.item.ar_title }}</span>
                <small class="text-muted">{{ order_item.ar_description }}</small>
              </div>
              <span class="btn btn-dark">{{ order_item.get_final_price }}EGP</span>
            </li>
            {% endfor %}

            {% if order.coupon %}
              <li class="list-group-item d-flex justify-content-between bg-light">
                  <div class="text-success">
                  <h6 class="my-0">Promo code</h6>
                  <span class="btn btn-light">{{ order.coupon.code }}</span>
                  </div>
                  <span class="btn btn-dark">-{{ order.coupon.amount }}EGP</span>
              </li>
              {% endif %}
            <li class="list-group-item d-flex justify-content-between">
              <span>Total (EGP)</span>
              <button class="btn btn-dark">{{ order.get_total_price }}</button>
            </li>

          </ul>
          <!-- Cart -->

 <!-- Promo code -->
         {% if DISPLAY_COUPON_FORM %}
          <form class="card p-2" action="{% url 'core:add-en-coupon' %}" method="POST">
              {% csrf_token %}
            <div class="input-group">
              <!--<input type="text" class="form-control" placeholder="Promo code" aria-label="Recipient's username" aria-describedby="basic-addon2">-->
                <span class="btn btn-dark">{{ couponform.code }}</span>
              <div class="input-group-append">
                <button class="btn btn-primary btn-md waves-effect m-0" type="submit">Redeem</button>
              </div>
            </div>
          </form>
            {% endif %}
          <!-- Promo code -->


        </div>